# Generated by Django 5.2.7 on 2026-02-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresionnivel",
            name="puntos_acumulativos",
            field=models.IntegerField(
                default=0, verbose_name="puntos acumulativos globales"
            ),
        ),
        migrations.AddField(
            model_name="progresionnivel",
            name="puntos_en_nivel",
            field=models.IntegerField(default=0, verbose_name="puntos en nivel actual"),
        ),
    ]
