# Generated by Django 6.0.1 on 2026-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_remove_perfilusuario_rol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("USUARIO", "Usuario"),
                    ("PREMIUM", "Premium"),
                    ("MODERADOR", "Moderador"),
                ],
                default="USUARIO",
                help_text="Rol de negocio. Para admin usar is_staff",
                max_length=20,
                verbose_name="rol",
            ),
        ),
    ]
