# Generated by Django 6.0.1 on 2026-02-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenido", "0002_lectura_dificultad_lectura_imagen_url_and_more"),
        ("usuarios", "0005_perfilusuario_rol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preferenciasusuario",
            name="modalidades_preferidas",
        ),
        migrations.AlterField(
            model_name="preferenciasusuario",
            name="categorias_preferidas",
            field=models.ManyToManyField(
                blank=True,
                help_text="TEMAS de interés: Ciencia, Deportes, Tecnología, Viajes...",
                related_name="usuarios_preferencias",
                to="contenido.categoria",
                verbose_name="categorías preferidas",
            ),
        ),
    ]
