# Generated by Django 5.2.7 on 2026-01-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CriterioHabilidad",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "peso_evaluacion",
                    models.IntegerField(default=1, verbose_name="peso en evaluación"),
                ),
            ],
            options={
                "verbose_name": "Criterio de Habilidad",
                "verbose_name_plural": "Criterios de Habilidad",
                "db_table": "criterio_habilidad",
                "ordering": ["nombre"],
            },
        ),
    ]
