# Generated by Django 5.2.7 on 2025-10-28 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="NivelDesempeno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("puntaje_min", models.DecimalField(decimal_places=2, max_digits=5)),
                ("puntaje_max", models.DecimalField(decimal_places=2, max_digits=5)),
                ("color", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="NivelEducativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ciclo", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RolUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Sesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_sesion", models.CharField(max_length=200)),
                ("objetivo_sesion", models.TextField()),
                ("horas_estimadas", models.IntegerField()),
                ("orden", models.IntegerField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("especialidad", models.CharField(max_length=100)),
                ("institucion", models.CharField(max_length=200)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_curso", models.CharField(max_length=20)),
                ("nombre_curso", models.CharField(max_length=200)),
                ("objetivo", models.TextField()),
                ("descripcion", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.docente",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.materia",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.niveleducativo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CriterioEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_criterio", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                ("orden", models.IntegerField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.sesion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_tema", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("orden", models.IntegerField()),
                ("semanas_estimadas", models.IntegerField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.curso",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sesion",
            name="tema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profesores.tema"
            ),
        ),
    ]
