# Generated by Django 5.2.4 on 2025-10-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niveldesempeno',
            old_name='puntaje_max',
            new_name='puntaje_maximo',
        ),
        migrations.RenameField(
            model_name='niveldesempeno',
            old_name='puntaje_min',
            new_name='puntaje_minimo',
        ),
        migrations.AlterField(
            model_name='niveldesempeno',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
