# Generated by Django 5.2.7 on 2026-01-12 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Logro",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                ("descripcion", models.TextField(verbose_name="descripción")),
                (
                    "criterios",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="criterios para desbloqueo",
                    ),
                ),
                (
                    "puntos_recompensa",
                    models.IntegerField(default=10, verbose_name="puntos recompensa"),
                ),
                (
                    "icono",
                    models.CharField(blank=True, max_length=100, verbose_name="icono"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Logro",
                "verbose_name_plural": "Logros",
                "db_table": "logro",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="LogroUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_obtencion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha obtención"
                    ),
                ),
                (
                    "notificacion_enviada",
                    models.BooleanField(
                        default=False, verbose_name="notificación enviada"
                    ),
                ),
                (
                    "logro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios_obtenidos",
                        to="logros.logro",
                        verbose_name="logro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logros_obtenidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logro del Usuario",
                "verbose_name_plural": "Logros del Usuario",
                "db_table": "logro_usuario",
                "ordering": ["-fecha_obtencion"],
                "indexes": [
                    models.Index(
                        fields=["usuario"], name="logro_usuar_usuario_8a3490_idx"
                    )
                ],
                "unique_together": {("usuario", "logro")},
            },
        ),
    ]
