# Generated by Django 5.2.7 on 2026-01-12 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenido", "0001_initial"),
        ("habilidades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_preguntas",
                    models.IntegerField(verbose_name="total preguntas"),
                ),
                (
                    "puntaje_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="puntaje total",
                    ),
                ),
                (
                    "puntajes_por_criterio",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="puntajes por criterio"
                    ),
                ),
                (
                    "recomendaciones_ia",
                    models.TextField(blank=True, verbose_name="recomendaciones IA"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INICIADA", "Iniciada"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="INICIADA",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha fin"
                    ),
                ),
                (
                    "duracion_segundos",
                    models.IntegerField(default=0, verbose_name="duración en segundos"),
                ),
                (
                    "lectura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones",
                        to="contenido.lectura",
                        verbose_name="lectura",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión",
                "verbose_name_plural": "Sesiones",
                "db_table": "sesion",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "respuesta",
                    models.CharField(max_length=500, verbose_name="respuesta"),
                ),
                (
                    "es_correcta",
                    models.BooleanField(default=False, verbose_name="es correcta"),
                ),
                (
                    "puntos_obtenidos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="puntos obtenidos",
                    ),
                ),
                (
                    "tiempo_respuesta_segundos",
                    models.IntegerField(
                        default=0, verbose_name="tiempo respuesta en segundos"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habilidades.criteriohabilidad",
                        verbose_name="criterio",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="contenido.pregunta",
                        verbose_name="pregunta",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="evaluacion.sesion",
                        verbose_name="sesión",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta",
                "verbose_name_plural": "Respuestas",
                "db_table": "respuesta",
                "ordering": ["sesion", "pregunta__orden"],
            },
        ),
        migrations.CreateModel(
            name="DesempenoCriterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intentos", models.IntegerField(default=0, verbose_name="intentos")),
                ("aciertos", models.IntegerField(default=0, verbose_name="aciertos")),
                (
                    "porcentaje_promedio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="porcentaje promedio",
                    ),
                ),
                (
                    "ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última actualización"
                    ),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desempenios",
                        to="habilidades.criteriohabilidad",
                        verbose_name="criterio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desempenios",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Desempeño de Criterio",
                "verbose_name_plural": "Desempeños de Criterio",
                "db_table": "desempenio_criterio",
                "ordering": ["usuario", "criterio"],
                "indexes": [
                    models.Index(
                        fields=["usuario"], name="desempenio__usuario_f64951_idx"
                    )
                ],
                "unique_together": {("usuario", "criterio")},
            },
        ),
        migrations.AddIndex(
            model_name="sesion",
            index=models.Index(fields=["usuario"], name="sesion_usuario_e7c2ec_idx"),
        ),
        migrations.AddIndex(
            model_name="sesion",
            index=models.Index(fields=["estado"], name="sesion_estado_63a13f_idx"),
        ),
        migrations.AddIndex(
            model_name="respuesta",
            index=models.Index(fields=["sesion"], name="respuesta_sesion__5e839d_idx"),
        ),
    ]
