# Generated by Django 5.2.7 on 2026-03-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluacion", "0003_add_skills_objetivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sesion",
            name="fecha_fin_plazo",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha fin plazo"
            ),
        ),
    ]
