# Generated by Django 5.2.7 on 2026-02-21 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RachaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dias_consecutivos",
                    models.IntegerField(default=0, verbose_name="días consecutivos"),
                ),
                (
                    "ultimo_acceso",
                    models.DateField(
                        blank=True, null=True, verbose_name="último acceso"
                    ),
                ),
                (
                    "ultima_lectura_fecha",
                    models.DateField(
                        blank=True, null=True, verbose_name="última lectura"
                    ),
                ),
                (
                    "fecha_ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha última actualización"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="racha",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Racha del Usuario",
                "verbose_name_plural": "Rachas de Usuarios",
                "db_table": "racha_usuario",
            },
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posicion", models.IntegerField(default=0, verbose_name="posición")),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking",
                "verbose_name_plural": "Rankings",
                "db_table": "ranking",
                "ordering": ["posicion"],
                "indexes": [
                    models.Index(fields=["posicion"], name="ranking_posicio_45bab9_idx")
                ],
            },
        ),
    ]
