# Generated by Django 6.0.1 on 2026-02-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0002_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="contraseña"),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table=None,
        ),
    ]
