# Generated by Django 5.2.7 on 2025-10-28 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumnos", "0001_initial"),
        ("evaluacion", "0001_initial"),
        ("profesores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluacionCriterioRespuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntaje_obtenido",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("puntaje_maximo", models.DecimalField(decimal_places=2, max_digits=5)),
                ("justificacion", models.TextField()),
                ("evidencia", models.TextField()),
                ("fecha_evaluacion", models.DateTimeField(auto_now_add=True)),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.criterioevaluacion",
                    ),
                ),
                (
                    "respuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluacion.respuestaalumno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReporteIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje_total", models.DecimalField(decimal_places=2, max_digits=5)),
                ("diagnostico_general", models.TextField()),
                ("fortalezas_identificadas", models.TextField()),
                ("areas_mejora", models.TextField()),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alumnos.alumno"
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluacion.evaluacion",
                    ),
                ),
                (
                    "nivel_desempeno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.niveldesempeno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecomendacionReporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_destinatario", models.CharField(max_length=20)),
                ("categoria", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                ("prioridad", models.CharField(max_length=20)),
                ("plazo_sugerido", models.CharField(max_length=50)),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reportes.reporteia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleReporteCriterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntaje_promedio",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("puntaje_maximo", models.DecimalField(decimal_places=2, max_digits=5)),
                ("nivel_desempeno", models.CharField(max_length=100)),
                ("diagnostico_criterio", models.TextField()),
                ("sugerencias_especificas", models.TextField()),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.criterioevaluacion",
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reportes.reporteia",
                    ),
                ),
            ],
        ),
    ]
