# Generated by Django 5.2.4 on 2025-10-29 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('evaluacion', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionCriterioRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('justificacion', models.TextField()),
                ('evidencia', models.TextField()),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.criterioevaluacion')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.respuestaalumno')),
            ],
            options={
                'db_table': 'evaluacion_criterio_respuesta',
            },
        ),
        migrations.CreateModel(
            name='ReporteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diagnostico_general', models.TextField()),
                ('fortalezas_identificadas', models.TextField()),
                ('areas_mejora', models.TextField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion')),
                ('nivel_desempeno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesores.niveldesempeno')),
            ],
            options={
                'db_table': 'reporte_ia',
            },
        ),
        migrations.CreateModel(
            name='RecomendacionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_destinatario', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('prioridad', models.CharField(max_length=20)),
                ('plazo_sugerido', models.CharField(max_length=50)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='reportes.reporteia')),
            ],
            options={
                'db_table': 'recomendacion_reporte',
            },
        ),
        migrations.CreateModel(
            name='DetalleReporteCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('nivel_desempeno', models.CharField(max_length=100)),
                ('diagnostico_criterio', models.TextField()),
                ('sugerencias_especificas', models.TextField()),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.criterioevaluacion')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reportes.reporteia')),
            ],
            options={
                'db_table': 'detalle_reporte_criterio',
            },
        ),
    ]
