# Generated by Django 5.2.4 on 2025-10-29 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_initial'),
        ('profesores', '0003_rename_puntaje_max_niveldesempeno_puntaje_maximo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='grado',
            new_name='grado_actual',
        ),
        migrations.AddField(
            model_name='alumno',
            name='colegio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre_tutor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='codigo_acceso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profesores.niveleducativo'),
        ),
    ]
