# Generated by Django 5.2.7 on 2026-02-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logro",
            name="icono",
            field=models.CharField(blank=True, max_length=10, verbose_name="icono"),
        ),
    ]
