# Generated by Django 5.2.7 on 2026-01-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NivelCEFR",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                ("vocab_min", models.IntegerField(verbose_name="vocabulario mínimo")),
                ("vocab_max", models.IntegerField(verbose_name="vocabulario máximo")),
                (
                    "cantidad_preguntas",
                    models.IntegerField(
                        default=15, verbose_name="cantidad de preguntas"
                    ),
                ),
                (
                    "distribucion_criterios",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="distribución de criterios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nivel CEFR",
                "verbose_name_plural": "Niveles CEFR",
                "db_table": "nivel_cefr",
                "ordering": ["codigo"],
            },
        ),
    ]
