# Generated by Django 5.2.7 on 2026-02-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("niveles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nivelcefr",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("BASICO", "Básico (A1-A2)"),
                    ("INTERMEDIO", "Intermedio (B1-B2)"),
                    ("AVANZADO", "Avanzado (C1-C2)"),
                ],
                default="BASICO",
                max_length=20,
                verbose_name="categoría",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nivelcefr",
            name="multiplicador_puntos",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=3,
                verbose_name="multiplicador de puntos",
            ),
        ),
        migrations.AddField(
            model_name="nivelcefr",
            name="puntos_requeridos",
            field=models.IntegerField(
                default=50, verbose_name="puntos requeridos para ascenso"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nivelcefr",
            name="cantidad_preguntas",
            field=models.IntegerField(default=10, verbose_name="cantidad de preguntas"),
        ),
    ]
