# Generated by Django 5.2.4 on 2025-10-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_evaluacion', models.CharField(max_length=200)),
                ('instrucciones', models.TextField()),
                ('fecha_aplicacion', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField()),
                ('tiempo_limite', models.IntegerField()),
                ('intentos_permitidos', models.IntegerField(default=1)),
                ('mostrar_resultados', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('orden', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pregunta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pregunta_criterio',
            },
        ),
        migrations.CreateModel(
            name='RespuestaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'respuesta_alumno',
            },
        ),
    ]
