# Generated by Django 5.2.7 on 2025-10-28 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumnos", "0001_initial"),
        ("profesores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_evaluacion", models.CharField(max_length=200)),
                ("instrucciones", models.TextField()),
                ("fecha_aplicacion", models.DateTimeField()),
                ("fecha_limite", models.DateTimeField()),
                ("tiempo_limite", models.IntegerField()),
                ("intentos_permitidos", models.IntegerField(default=1)),
                ("mostrar_resultados", models.BooleanField(default=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.docente",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.sesion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_pregunta", models.TextField()),
                ("orden", models.IntegerField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.sesion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreguntaCriterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.criterioevaluacion",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluacion.pregunta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_respuesta", models.TextField()),
                ("fecha_respuesta", models.DateTimeField(auto_now_add=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alumnos.alumno"
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluacion.evaluacion",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluacion.pregunta",
                    ),
                ),
            ],
        ),
    ]
