# Generated by Django 5.2.4 on 2025-10-29 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('evaluacion', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.docente'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.sesion'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='profesores.sesion'),
        ),
        migrations.AddField(
            model_name='preguntacriterio',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.criterioevaluacion'),
        ),
        migrations.AddField(
            model_name='preguntacriterio',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.pregunta'),
        ),
        migrations.AddField(
            model_name='respuestaalumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='respuestaalumno',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion'),
        ),
        migrations.AddField(
            model_name='respuestaalumno',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.pregunta'),
        ),
        migrations.AlterUniqueTogether(
            name='preguntacriterio',
            unique_together={('pregunta', 'criterio')},
        ),
    ]
