# Generated by Django 5.2.7 on 2026-01-12 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("niveles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("ESTUDIANTE", "Estudiante"),
                            ("PROFESOR", "Profesor"),
                        ],
                        default="ESTUDIANTE",
                        max_length=20,
                        verbose_name="rol",
                    ),
                ),
                (
                    "puntos_totales",
                    models.IntegerField(default=0, verbose_name="puntos totales"),
                ),
                (
                    "lecturas_completadas",
                    models.IntegerField(default=0, verbose_name="lecturas completadas"),
                ),
                (
                    "nivel_cefr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="niveles.nivelcefr",
                        verbose_name="nivel CEFR",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_hackaedu",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
                "db_table": "perfil_usuario",
            },
        ),
        migrations.CreateModel(
            name="ProgresionNivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lecturas_completadas_en_nivel",
                    models.IntegerField(
                        default=0, verbose_name="lecturas completadas en nivel"
                    ),
                ),
                (
                    "promedio_puntos_en_nivel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="promedio puntos en nivel",
                    ),
                ),
                (
                    "criterios_dominados",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="criterios dominados"
                    ),
                ),
                (
                    "listo_para_ascenso",
                    models.BooleanField(
                        default=False, verbose_name="listo para ascenso"
                    ),
                ),
                (
                    "ascenso_ofrecido",
                    models.BooleanField(default=False, verbose_name="ascenso ofrecido"),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha actualización"
                    ),
                ),
                (
                    "nivel_actual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="niveles.nivelcefr",
                        verbose_name="nivel actual",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresión de Nivel",
                "verbose_name_plural": "Progresiones de Nivel",
                "db_table": "progresion_nivel",
            },
        ),
    ]
