# Generated by Django 6.0.1 on 2026-02-21 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenido", "0002_lectura_dificultad_lectura_imagen_url_and_more"),
        ("usuarios", "0002_progresionnivel_puntos_acumulativos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferenciasUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dificultad_inicial",
                    models.CharField(
                        choices=[
                            ("BASIC", "Básica (1-2)"),
                            ("INTERMEDIATE", "Intermedia (3-4)"),
                            ("ADVANCED", "Avanzada (5-6)"),
                            ("EXPERT", "Experto (7+)"),
                        ],
                        default="BASIC",
                        max_length=20,
                        verbose_name="dificultad inicial",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "categorias_preferidas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="usuarios_preferencias",
                        to="contenido.categoria",
                        verbose_name="categorías preferidas",
                    ),
                ),
                (
                    "modalidades_preferidas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="usuarios_preferencias",
                        to="contenido.modalidad",
                        verbose_name="modalidades preferidas",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencias de Usuario",
                "verbose_name_plural": "Preferencias de Usuarios",
                "db_table": "preferencias_usuario",
            },
        ),
    ]
