# Generated by Django 6.0.1 on 2026-02-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenido", "0002_lectura_dificultad_lectura_imagen_url_and_more"),
        ("usuarios", "0003_preferenciasusuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfilusuario",
            name="rol",
        ),
        migrations.AlterField(
            model_name="preferenciasusuario",
            name="categorias_preferidas",
            field=models.ManyToManyField(
                blank=True,
                help_text="TEMAS de interés: Travel, Business, Technology...",
                related_name="usuarios_preferencias",
                to="contenido.categoria",
                verbose_name="categorías preferidas",
            ),
        ),
        migrations.AlterField(
            model_name="preferenciasusuario",
            name="modalidades_preferidas",
            field=models.ManyToManyField(
                blank=True,
                help_text="FORMATOS preferidos: News, Stories, Academic...",
                related_name="usuarios_preferencias",
                to="contenido.modalidad",
                verbose_name="modalidades preferidas",
            ),
        ),
    ]
