# Generated by Django 5.2.7 on 2026-01-12 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habilidades", "0001_initial"),
        ("niveles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "icono",
                    models.CharField(blank=True, max_length=50, verbose_name="icono"),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "categoria",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Modalidad",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="activa")),
            ],
            options={
                "verbose_name": "Modalidad",
                "verbose_name_plural": "Modalidades",
                "db_table": "modalidad",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Lectura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="título")),
                ("contenido", models.TextField(verbose_name="contenido")),
                (
                    "palabras_count",
                    models.IntegerField(default=0, verbose_name="contador de palabras"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "publicada",
                    models.BooleanField(default=False, verbose_name="publicada"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenido.categoria",
                        verbose_name="categoría",
                    ),
                ),
                (
                    "nivel_cefr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="niveles.nivelcefr",
                        verbose_name="nivel CEFR",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturas_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario creador",
                    ),
                ),
                (
                    "modalidad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenido.modalidad",
                        verbose_name="modalidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lectura",
                "verbose_name_plural": "Lecturas",
                "db_table": "lectura",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(verbose_name="texto de pregunta")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MULTIPLE", "Opción Múltiple"),
                            ("COMPLETAR", "Completar"),
                            ("VERDADERO_FALSO", "Verdadero/Falso"),
                        ],
                        default="MULTIPLE",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "opciones",
                    models.JSONField(blank=True, default=list, verbose_name="opciones"),
                ),
                (
                    "respuesta_correcta",
                    models.CharField(max_length=500, verbose_name="respuesta correcta"),
                ),
                (
                    "explicacion",
                    models.TextField(blank=True, verbose_name="explicación"),
                ),
                ("orden", models.IntegerField(default=0, verbose_name="orden")),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="habilidades.criteriohabilidad",
                        verbose_name="criterio de habilidad",
                    ),
                ),
                (
                    "lectura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="contenido.lectura",
                        verbose_name="lectura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "db_table": "pregunta",
                "ordering": ["lectura", "orden"],
            },
        ),
        migrations.AddIndex(
            model_name="lectura",
            index=models.Index(
                fields=["nivel_cefr"], name="lectura_nivel_c_144537_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lectura",
            index=models.Index(fields=["categoria"], name="lectura_categor_02ef0b_idx"),
        ),
        migrations.AddIndex(
            model_name="lectura",
            index=models.Index(fields=["publicada"], name="lectura_publica_a6e7de_idx"),
        ),
        migrations.AddIndex(
            model_name="pregunta",
            index=models.Index(fields=["lectura"], name="pregunta_lectura_eb31b5_idx"),
        ),
    ]
