# Generated by Django 5.2.7 on 2026-02-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenido", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lectura",
            name="dificultad",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic (1-2)"),
                    ("INTERMEDIATE", "Intermediate (3-4)"),
                    ("ADVANCED", "Advanced (5-6)"),
                    ("EXPERT", "Expert (7+)"),
                ],
                default="BASIC",
                max_length=20,
                verbose_name="dificultad",
            ),
        ),
        migrations.AddField(
            model_name="lectura",
            name="imagen_url",
            field=models.URLField(
                blank=True,
                help_text="Imagen personalizada (scraping futuro). Si está vacía, usa genérica de categoría",
                null=True,
                verbose_name="URL de imagen",
            ),
        ),
        migrations.AddField(
            model_name="lectura",
            name="puntos_base",
            field=models.IntegerField(
                default=1,
                help_text="Puntos base por pregunta (se multiplica por dificultad)",
                verbose_name="puntos base",
            ),
        ),
        migrations.AddField(
            model_name="pregunta",
            name="puntos_directos",
            field=models.IntegerField(
                default=1,
                help_text="Puntos base * multiplicador de dificultad = puntos finales",
                verbose_name="puntos directos",
            ),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="opciones",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Para MULTIPLE: ["opción1", "opción2", "opción3", "opción4"] (máximo 4)',
                verbose_name="opciones",
            ),
        ),
    ]
